level_0 = {
    'terrain' : '../levels/level 0/level_0_terrain.csv',
    'coins' : '../levels/level 0/level_0_coins.csv',
    'health' : '../levels/level 0/level_0_health.csv',
    'fg_palms' : '../levels/level 0/level_0_fg palms.csv',
    'bg_palms' : '../levels/level 0/level_0_bg palms.csv',
    'crates' : '../levels/level 0/level_0_crates.csv',
    'enemies' : '../levels/level 0/level_0_enemies.csv',
    'shell' : '../levels/level 0/level_0_shell.csv',
    'constraints' : '../levels/level 0/level_0_constraints.csv',
    'player' : '../levels/level 0/level_0_player.csv',
    'grass' : '../levels/level 0/level_0_grass.csv',
    'moving platform' : '../levels/level 0/level_0_moving_platforms.csv',
    'spikes' : '../levels/level 0/level_0_spikes.csv',
    'treasure': '../levels/level 0/level_0_treasure.csv',
    'boss': '../levels/level 0/level_0_boss.csv',
    'node_pos' : (110, 400),
    'unlock' : 1,
    'node_graphics' : '../graphics/overworld/0',
    'vertical_tile_num' : 13
}

level_1 = {
    'terrain' : '../levels/level 1/level_1_terrain.csv',
    'coins' : '../levels/level 1/level_1_coins.csv',
    'health' : '../levels/level 1/level_1_health.csv',
    'fg_palms' : '../levels/level 1/level_1_fg palms.csv',
    'bg_palms' : '../levels/level 1/level_1_bg palms.csv',
    'crates' : '../levels/level 1/level_1_crates.csv',
    'enemies' : '../levels/level 1/level_1_enemies.csv',
    'shell' : '../levels/level 1/level_1_shell.csv',
    'constraints' : '../levels/level 1/level_1_constraints.csv',
    'player' : '../levels/level 1/level_1_player.csv',
    'grass' : '../levels/level 1/level_1_grass.csv',
    'moving platform' : '../levels/level 1/level_1_moving_platforms.csv',
    'spikes' : '../levels/level 1/level_1_spikes.csv',
    'treasure': '../levels/level 1/level_1_treasure.csv',
    'boss': '../levels/level 1/level_1_boss.csv',
    'node_pos' : (300, 220),
    'unlock' : 2,
    'node_graphics' : '../graphics/overworld/1',
    'vertical_tile_num' : 13
}

level_2 = {
    'terrain' : '../levels/level 2/level_2_terrain.csv',
    'coins' : '../levels/level 2/level_2_coins.csv',
    'health' : '../levels/level 2/level_2_health.csv',
    'fg_palms' : '../levels/level 2/level_2_fg palms.csv',
    'bg_palms' : '../levels/level 2/level_2_bg palms.csv',
    'crates' : '../levels/level 2/level_2_crates.csv',
    'enemies' : '../levels/level 2/level_2_enemies.csv',
    'shell' : '../levels/level 2/level_2_shell.csv',
    'constraints' : '../levels/level 2/level_2_constraints.csv',
    'player' : '../levels/level 2/level_2_player.csv',
    'grass' : '../levels/level 2/level_2_grass.csv',
    'moving platform' : '../levels/level 2/level_2_moving_platforms.csv',
    'spikes' : '../levels/level 2/level_2_spikes.csv',
    'treasure': '../levels/level 2/level_2_treasure.csv',
    'boss': '../levels/level 2/level_2_boss.csv',
    'node_pos' : (480, 610),
    'unlock' : 3,
    'node_graphics' : '../graphics/overworld/2',
    'vertical_tile_num' : 13
}

level_3 = {
    'terrain' : '../levels/level 3/level_3_terrain.csv',
    'coins' : '../levels/level 3/level_3_coins.csv',
    'health' : '../levels/level 3/level_3_health.csv',
    'fg_palms' : '../levels/level 3/level_3_fg palms.csv',
    'bg_palms' : '../levels/level 3/level_3_bg palms.csv',
    'crates' : '../levels/level 3/level_3_crates.csv',
    'enemies' : '../levels/level 3/level_3_enemies.csv',
    'shell' : '../levels/level 3/level_3_shell.csv',
    'constraints' : '../levels/level 3/level_3_constraints.csv',
    'player' : '../levels/level 3/level_3_player.csv',
    'grass' : '../levels/level 3/level_3_grass.csv',
    'moving platform' : '../levels/level 3/level_3_moving_platforms.csv',
    'spikes' : '../levels/level 3/level_3_spikes.csv',
    'treasure' : '../levels/level 3/level_3_treasure.csv',
    'boss': '../levels/level 3/level_3_boss.csv',
    'node_pos' : (610, 350),
    'unlock' : 4,
    'node_graphics' : '../graphics/overworld/3',
    'vertical_tile_num' : 13
}

level_4 = {
    'terrain' : '../levels/level 4/level_4_terrain.csv',
    'coins' : '../levels/level 4/level_4_coins.csv',
    'health' : '../levels/level 4/level_4_health.csv',
    'fg_palms' : '../levels/level 4/level_4_fg palms.csv',
    'bg_palms' : '../levels/level 4/level_4_bg palms.csv',
    'crates' : '../levels/level 4/level_4_crates.csv',
    'enemies' : '../levels/level 4/level_4_enemies.csv',
    'shell' : '../levels/level 4/level_4_shell.csv',
    'constraints' : '../levels/level 4/level_4_constraints.csv',
    'player' : '../levels/level 4/level_4_player.csv',
    'grass' : '../levels/level 4/level_4_grass.csv',
    'moving platform' : '../levels/level 4/level_4_moving_platforms.csv',
    'spikes' : '../levels/level 4/level_4_spikes.csv',
    'treasure' : '../levels/level 4/level_4_treasure.csv',
    'boss' : '../levels/level 4/level_4_boss.csv',
    'node_pos' : (880, 210),
    'unlock' : 5,
    'node_graphics' : '../graphics/overworld/4',
    'vertical_tile_num' : 60
}

level_5 = {
    'terrain' : '../levels/level 5/level_5_terrain.csv',
    'coins' : '../levels/level 5/level_5_coins.csv',
    'health' : '../levels/level 5/level_5_health.csv',
    'fg_palms' : '../levels/level 5/level_5_fg palms.csv',
    'bg_palms' : '../levels/level 5/level_5_bg palms.csv',
    'crates' : '../levels/level 5/level_5_crates.csv',
    'enemies' : '../levels/level 5/level_5_enemies.csv',
    'shell' : '../levels/level 5/level_5_shell.csv',
    'constraints' : '../levels/level 5/level_5_constraints.csv',
    'player' : '../levels/level 5/level_5_player.csv',
    'grass' : '../levels/level 5/level_5_grass.csv',
    'moving platform' : '../levels/level 5/level_5_moving_platforms.csv',
    'spikes' : '../levels/level 5/level_5_spikes.csv',
    'treasure' : '../levels/level 5/level_5_treasure.csv',
    'boss' : '../levels/level 5/level_5_boss.csv',
    'node_pos' : (1050, 400),
    'unlock' : 6,
    'node_graphics' : '../graphics/overworld/5',
    'vertical_tile_num' : 13
}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5
}